version: 2.1

orbs:
  hello: circleci/hello-build@0.0.7

workflows:
  "Hello Workflow":
    jobs:
      build:
        docker:
          - image: cricleci/node:4.8.2
        steps:
          - checkout
          - run: echo "Hey there friend"