version: 2

jobs:
  deploy-production:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Master to ben-littleton.com
          command: | 
            ssh circleci@ben-littleton.com "cd webroot/html && sudo -u www-data git pull"
  deploy-staging:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Staging to staging.ben-littleton.com
          command: |
            ssh circleci@ben-littleton.com "cd webroot/personal-site-staging && sudo -u www-data git pull"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-production:
          filters:
            branches:
              only: master
      - deploy-staging:
          filters:
            branches:
              only: staging

