version: 2

jobs:
  deploy-production:
    run:
      - ssh circleci@ben-littleton.com "cd webroot/html && sudo -u www-data git pull"
      - echo "Deployed master branch to ben-littleton.com"
  deploy-staging:
    run:
      - ssh circleci@ben-littleton.com "cd webroot/personal-site-staging && sudo -u www-data git pull"
      - echo "Deployed staging branch to staging.ben-littleton.com"

worksflows:
  version: 2
  deploy:
    jobs:
      - deploy-production:
          filters:
            branches:
              only: master
      - deploy-staging:
          filters:
            branches:
              only: staging

